name: Auto Website Scraper

on:
  schedule:
    - cron: '0 * * * *' # हर 1 घंटे में बैकग्राउंड में स्क्रिप्ट खुद चालू होगी
  workflow_dispatch: # मैन्युअल रूप से बटन दबाकर चालू करने के लिए

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install requests beautifulsoup4 cloudscraper lxml httpx telethon motor

    - name: Run Scraper Script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        TELEGRAM_API: ${{ secrets.TELEGRAM_API }}
        TELEGRAM_HASH: ${{ secrets.TELEGRAM_HASH }}
        BIN_CHANNEL: ${{ secrets.BIN_CHANNEL }} # गिटहब सीक्रेट्स से बिन चैनल आईडी
        TARGET_SCRAPE_URL: "https://netmirror.center/"
      run: |
        python -u scraper.py
